#!/usr/bin/env python3
"""Write the per-terminal work lists for the connector data-sourcing run (data-sourcing/README.md).

Every published connector goes to exactly one of four parts. A provider's connectors stay in
one part (one terminal reads Google's docs once, not four times), and the parts are balanced by
the number of missing facts. Inputs are derived from src/lib/connectors.json; re-run any time.
"""
import csv, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'data-sourcing', 'inputs')
PARTS = 4
LINKS = ('site', 'portal', 'api', 'authDocs', 'whDocs', 'statusUrl')


def has_logo(c):
    return bool(c.get('logo')) and os.path.isfile(os.path.join(ROOT, 'public', c['logo'].lstrip('/')))


def tool_counts(caps):
    rd = sum(int(m.group(1)) for x in caps for m in [re.match(r'(\d+) read tools?$', x)] if m)
    wr = sum(int(m.group(1)) for x in caps for m in [re.match(r'(\d+) write tools?$', x)] if m)
    return rd, wr


def needs(c):
    n = []
    if not has_logo(c):
        n.append('logo')
    n += [k for k in LINKS if not c.get(k) and (k != 'whDocs' or c.get('wh'))]
    if c.get('auth') in ('See documentation', 'Provider-specific', '', None):
        n.append('auth')
    if not c.get('scopes'):
        n.append('scopes')
    named = [x for x in c.get('caps', []) if not re.match(r'\d+ (read|write) tools?$', x)]
    if not named:
        n.append('caps')
    if not c.get('reqs'):
        n.append('reqs')
    return n


def main():
    rows = [c for c in json.load(open(os.path.join(ROOT, 'src', 'lib', 'connectors.json'))) if not c['unpublished']]
    groups = {}
    for c in rows:
        groups.setdefault((c.get('p') or c['n']).strip().lower(), []).append(c)
    weight = lambda g: sum(len(needs(c)) + (2 if 'logo' in needs(c) else 0) for c in g)
    parts = [[] for _ in range(PARTS)]
    load = [0] * PARTS
    for g in sorted(groups.values(), key=weight, reverse=True):
        i = load.index(min(load))
        parts[i] += g
        load[i] += weight(g)
    os.makedirs(OUT, exist_ok=True)
    cols = ['id', 'name', 'provider', 'category', 'auth_now', 'webhooks', *LINKS, 'core_read_tools', 'core_write_tools', 'needs']
    summary = []
    for i, part in enumerate(parts, 1):
        part.sort(key=lambda c: ((c.get('p') or '').lower(), c['id']))
        with open(os.path.join(OUT, f'part-{i}.csv'), 'w', newline='') as f:
            w = csv.writer(f)
            w.writerow(cols)
            for c in part:
                rd, wr = tool_counts(c.get('caps', []))
                w.writerow([c['id'], c['n'], c.get('p') or '', c['cat'], c.get('auth') or '', 'yes' if c.get('wh') else 'no',
                            *[c.get(k) or '' for k in LINKS], rd, wr, ';'.join(needs(c))])
        cnt = {}
        for c in part:
            for k in needs(c):
                cnt[k] = cnt.get(k, 0) + 1
        summary.append((i, len(part), cnt))
    keys = ['logo', *LINKS, 'auth', 'caps', 'scopes', 'reqs']
    with open(os.path.join(OUT, 'SUMMARY.md'), 'w') as f:
        f.write(f'# Data-sourcing inputs\n\nGenerated by `scripts/data-sourcing-inputs.py` from `src/lib/connectors.json` ({len(rows)} published connectors).\n\n')
        f.write('| Part | Connectors | ' + ' | '.join(keys) + ' |\n|---|---:|' + '---:|' * len(keys) + '\n')
        for i, n, cnt in summary:
            f.write(f'| {i} | {n} | ' + ' | '.join(str(cnt.get(k, 0)) for k in keys) + ' |\n')
        tot = {k: sum(s[2].get(k, 0) for s in summary) for k in keys}
        f.write(f'| **all** | **{len(rows)}** | ' + ' | '.join(f'**{tot[k]}**' for k in keys) + ' |\n')
    print(open(os.path.join(OUT, 'SUMMARY.md')).read())


if __name__ == '__main__':
    main()
