#!/usr/bin/env python3
"""Catalogue reconciliation: website snapshot vs the Connector OS core registry.

The website's src/lib/connectors.json is a frozen snapshot (the ZIP's
"1000"). The authoritative catalogue lives in the core repo
(connector-os-read-api). This script compares the two and writes a
reconciliation report. It never edits connectors.json — promotion, aliasing
and retirement decisions belong to the core programme (Lane 6), and the
website regenerates from core once they are made.

Usage:
  # against a local core checkout (scans packages/connectors/*/manifest.json —
  # the path every snapshot row cites in source_provenance)
  python3 scripts/reconcile-catalogue.py --core "/path/to/connector-os-read-api"

  # against an exported id list (CSV with an id/slug column, or JSON list of
  # ids / objects with an "id" field), e.g. FINAL_1000_IDENTITY_LIST.csv
  python3 scripts/reconcile-catalogue.py --ids core-ids.csv

  # snapshot-only report (no core available) — what this repo can prove alone
  python3 scripts/reconcile-catalogue.py --self

  --out FILE    write the markdown report to FILE (default: stdout)
  --strict      exit 1 when the snapshot and core disagree on membership
"""
import csv, glob, json, os, sys, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CANON = os.path.join(ROOT, 'src', 'lib', 'connectors.json')
LEGACY = os.path.join(ROOT, 'src', 'lib', 'connectors-legacy.json')

# Providers the brief requires an explicit answer for, plus common staging names.
MAJOR = ['openai', 'anthropic', 'azure-openai', 'google-gemini', 'github', 'slack',
         'notion', 'gmail', 'google-drive', 'stripe', 'salesforce', 'hubspot',
         'shopify', 'linear', 'jira', 'zendesk', 'microsoft-teams', 'twilio']


def arg(name):
    return sys.argv[sys.argv.index(name) + 1] if name in sys.argv else None


def core_from_repo(path):
    """{id: manifest-dict} from <core>/packages/connectors/*/manifest.json."""
    out = {}
    for mf in sorted(glob.glob(os.path.join(path, 'packages', 'connectors', '*', 'manifest.json'))):
        d = os.path.basename(os.path.dirname(mf))
        try:
            m = json.load(open(mf))
        except Exception as e:  # report, don't guess
            m = {'_error': str(e)}
        cid = m.get('id') or m.get('slug') or d
        out[cid] = {**m, '_dir': d}
    return out


def core_from_ids(path):
    if path.endswith('.json'):
        data = json.load(open(path))
        return {(x['id'] if isinstance(x, dict) else x): (x if isinstance(x, dict) else {}) for x in data}
    with open(path, newline='') as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return {}
    key = next((k for k in rows[0] if k and k.lower() in ('id', 'slug', 'connector_id', 'canonical_id')), None)
    if not key:
        sys.exit(f'no id/slug column in {path}: columns are {list(rows[0])}')
    return {r[key].strip(): r for r in rows if r[key].strip()}


def main():
    can = json.load(open(CANON))
    leg = json.load(open(LEGACY))
    cid = {c['id']: c for c in can}
    lid = {c['id']: c for c in leg}
    alias_ids = {c['alias_of']: c['id'] for c in can if c.get('alias_of')}

    core, source = None, None
    if arg('--core'):
        core, source = core_from_repo(arg('--core')), f"manifests under {arg('--core')}/packages/connectors"
        if not core:
            sys.exit(f'no manifests found under {arg("--core")}/packages/connectors/*/manifest.json')
    elif arg('--ids'):
        core, source = core_from_ids(arg('--ids')), arg('--ids')
    elif '--self' not in sys.argv:
        sys.exit(__doc__)

    L = []
    w = L.append
    pub = [c for c in can if not c.get('unpublished')]
    w('# Catalogue reconciliation report\n')
    w(f'Website snapshot: `src/lib/connectors.json` — generated by `scripts/reconcile-catalogue.py`.\n')
    w('## Website snapshot (this repo)\n')
    w('| Measure | Value |\n|---|---|')
    w(f'| Canonical rows | {len(can)} |')
    w(f'| Published (rendered on /connectors) | {len(pub)} |')
    w(f'| Unpublished / HOLD | {len(can) - len(pub)} |')
    w(f'| Unique ids | {len(cid)} |')
    w(f'| Rank range | {min(c["r"] for c in can)}–{max(c["r"] for c in can)} |')
    w(f'| Runtime-verified | {sum(1 for c in can if c.get("runtime_status", "not_verified") != "not_verified")} |')
    w(f'| Categories | {len({c["cat"] for c in can})} |')
    w(f'| Alias rows (`alias_of` set) | {len(alias_ids)} — targets in canonical: {sum(1 for t in alias_ids if t in cid)}, in legacy: {sum(1 for t in alias_ids if t in lid)} |')
    w(f'| Legacy reference rows | {len(leg)} |')
    w('')
    w('### Catalogue status × publication\n')
    w('| Catalogue status | Published | HOLD |\n|---|---|---|')
    for s, n in collections.Counter(c['s'] for c in can).most_common():
        p = sum(1 for c in pub if c['s'] == s)
        w(f'| {s} | {p} | {n - p} |')
    w('\n### HOLD categories\n')
    w('| Hold category | Rows |\n|---|---|')
    for h, n in collections.Counter(c.get('hold_category') for c in can if c.get('unpublished')).most_common():
        w(f'| {h} | {n} |')
    w('\n### Legacy rows by Lane 6 classification / route behaviour\n')
    w('| Classification | Behaviour | Rows |\n|---|---|---|')
    for (k, b), n in sorted(collections.Counter((c.get('lane6_classification'), c.get('lane6_behavior')) for c in leg).items(), key=lambda x: -x[1]):
        w(f'| {k} | {b} | {n} |')

    w('\n## Major providers\n')
    hdr = '| Provider id | Canonical (snapshot) | Legacy (snapshot) |' + (' In core |' if core is not None else '')
    w(hdr + '\n|---|---|---|' + ('---|' if core is not None else ''))
    for m in MAJOR:
        c = cid.get(m)
        cs = f"rank {c['r']}, {c['s']}{', HOLD' if c.get('unpublished') else ''}" if c else ('alias id → ' + alias_ids[m] if m in alias_ids else 'no')
        lg = lid.get(m)
        ls = f"{lg['lane6_classification']} / {lg['lane6_behavior']}" if lg else 'no'
        row = f'| `{m}` | {cs} | {ls} |'
        if core is not None:
            row += f" {'yes' if m in core else 'no'} |"
        w(row)

    rc = 0
    if core is not None:
        w(f'\n## Against core ({source})\n')
        core_ids = set(core)
        snap = set(cid)
        missing = sorted(core_ids - snap)              # in core, absent from website canonical
        extra = sorted(snap - core_ids)                # on website, absent from core
        promoted = sorted(i for i in missing if i in lid)       # legacy rows now canonical in core
        alias_hit = sorted(i for i in missing if i in alias_ids)  # core uses the alias id
        new = sorted(set(missing) - set(promoted) - set(alias_hit))
        w('| Measure | Value |\n|---|---|')
        w(f'| Core total | {len(core_ids)} |')
        w(f'| Website canonical total | {len(snap)} |')
        w(f'| In both | {len(core_ids & snap)} |')
        w(f'| In core, missing from website | {len(missing)} |')
        w(f'| … of which are website legacy rows (promote) | {len(promoted)} |')
        w(f'| … of which match a website alias_of id (re-key) | {len(alias_hit)} |')
        w(f'| … of which are new to the website | {len(new)} |')
        w(f'| On website, not in core (retired / renamed?) | {len(extra)} |')
        for title, ids in (('Promote from legacy', promoted), ('Re-key alias', alias_hit), ('New in core', new), ('Website-only', extra)):
            if ids:
                w(f'\n### {title} ({len(ids)})\n')
                w(', '.join(f'`{i}`' for i in ids))
        rc = 1 if (missing or extra) and '--strict' in sys.argv else 0
        w('\nNext step: regenerate `src/lib/connectors.json` from core (with publication policy applied), then re-run `npm run gates`. Do not hand-append rows.')
    else:
        w('\n## Against core\n')
        w('Not run — no core checkout or id export was supplied. Run with `--core <path>` on a machine that has `connector-os-read-api`.')

    out = '\n'.join(L) + '\n'
    if arg('--out'):
        open(arg('--out'), 'w').write(out)
        print(f'wrote {arg("--out")}')
    else:
        sys.stdout.write(out)
    return rc


if __name__ == '__main__':
    sys.exit(main())
