#!/usr/bin/env python3
"""What connector data is still missing after the ingest, and the work lists for the next round.

  python3 scripts/remaining-gaps.py        # writes data-sourcing/REMAINING_DATA.md + inputs/part-5.csv, part-6.csv

Reads the synced catalogue (src/lib/connectors.json), so run it after
`ingest-sourced-data.py && npm run sync:catalogue`. Part numbers continue the
first round (1-4): the ingest lets a later part supersede an earlier one per field.
"""
import csv, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DS = os.path.join(ROOT, 'data-sourcing')
LINKS = ('site', 'portal', 'api', 'authDocs', 'whDocs', 'statusUrl')
# field -> (priority, where the fact comes from)
SOURCES = {
    'logo': ('P1', "press/brand kit, or the SVG in the provider's website header (square mark)"),
    'site': ('P1', "the provider's own homepage (HTTP 200 in a browser)"),
    'portal': ('P1', 'developer portal / docs home, linked from the homepage footer or nav'),
    'api': ('P1', 'API reference page (often /reference, /api, or a Postman/Stoplight page the portal links to)'),
    'auth': ('P1', 'authentication page of the API docs'),
    'caps': ('P2', 'API reference: 5-25 main operations, method + path as documented'),
    'reqs': ('P2', 'getting-started / authentication page: account, plan, key or OAuth app needed'),
    'authDocs': ('P2', 'authentication / API keys / OAuth page'),
    'scopes': ('P3', 'OAuth scopes or key-permissions page; for API-key products the scope model only'),
    'whDocs': ('P3', 'webhooks page (only when the provider documents webhooks)'),
    'statusUrl': ('P3', 'status page (often status.<domain>); many providers have none, so notFound is a valid answer'),
}


def has_logo(c):
    return bool(c.get('logo')) and os.path.isfile(os.path.join(ROOT, 'public', c['logo'].lstrip('/')))


def needs(c):
    n = []
    if not has_logo(c):
        n.append('logo')
    n += [k for k in LINKS if not c.get(k) and (k != 'whDocs' or c.get('wh'))]
    if c.get('auth') in ('See documentation', '', None):  # 'Provider-specific' is a documented answer
        n.append('auth')
    if not c.get('providerCaps') and not [x for x in c.get('caps', []) if 'tools' not in x]:
        n.append('caps')
    if not c.get('scopeModel') and not c.get('scopes'):
        n.append('scopes')
    if not c.get('reqs'):
        n.append('reqs')
    return n


def main():
    rows = [c for c in json.load(open(os.path.join(ROOT, 'src', 'lib', 'connectors.json'))) if not c['unpublished']]
    gaps = {c['id']: needs(c) for c in rows}
    todo = [c for c in rows if gaps[c['id']] and c['id'] != 'egnyte']  # egnyte: separate lane
    p1 = [c for c in todo if any(SOURCES[k][0] == 'P1' for k in gaps[c['id']])]
    # balance two parts by provider group, like the first round
    groups = {}
    for c in todo:
        groups.setdefault((c.get('p') or c['n']).lower(), []).append(c)
    parts, load = [[], []], [0, 0]
    for g in sorted(groups.values(), key=lambda g: -sum(len(gaps[c['id']]) for c in g)):
        i = load.index(min(load))
        parts[i] += g
        load[i] += sum(len(gaps[c['id']]) for c in g)
    cols = ['id', 'name', 'provider', 'category', 'auth_now', 'webhooks', *LINKS, 'needs', 'review_state']
    os.makedirs(os.path.join(DS, 'inputs'), exist_ok=True)
    for i, part in enumerate(parts, 5):
        with open(os.path.join(DS, 'inputs', f'part-{i}.csv'), 'w', newline='') as f:
            w = csv.writer(f)
            w.writerow(cols)
            for c in sorted(part, key=lambda c: ((c.get('p') or '').lower(), c['id'])):
                w.writerow([c['id'], c['n'], c.get('p') or '', c['cat'], c.get('auth') or '', 'yes' if c.get('wh') else 'no',
                            *[c.get(k) or '' for k in LINKS], ';'.join(gaps[c['id']]), c.get('data_review') or ''])
    count = {k: sum(1 for v in gaps.values() if k in v) for k in SOURCES}
    L = ['# Remaining connector data (after round 1: parts 1-4)', '',
         f'Generated by `scripts/remaining-gaps.py` from the synced catalogue: {len(rows)} published connectors.', '',
         f'- **{len(rows) - len(todo) - (1 if "egnyte" in gaps else 0)}** connectors are complete for every field below.',
         f'- **{len(todo)}** still miss at least one field; **{len(p1)}** of those miss a P1 field (logo, site, portal, API reference or auth method).',
         '- Egnyte is a separate lane and is not in these lists.', '',
         '| Field | Priority | Missing | Where it comes from |', '|---|---|---:|---|']
    L += [f'| {k} | {pr} | {count[k]} | {src} |' for k, (pr, src) in SOURCES.items()]
    L += ['', 'P1 is what a visitor sees first; do it before anything else. P3 fields legitimately do not exist for many providers: `notFound` is a valid, final answer for them.', '',
          '## Round 2: two terminals', '',
          '| Terminal | Input | Return to |', '|---|---|---|',
          f'| 1 | `data-sourcing/inputs/part-5.csv` ({len(parts[0])} connectors) | `data-sourcing/returns/part-5/` |',
          f'| 2 | `data-sourcing/inputs/part-6.csv` ({len(parts[1])} connectors) | `data-sourcing/returns/part-6/` |', '',
          'Use the prompt in `data-sourcing/README.md` §4 with `PART=5` / `PART=6`. Research only the fields in the `needs` column.',
          'A record only needs the fields it adds: the ingest merges it over the round-1 record, field by field. The same rules apply: official sources, an evidence URL per fact, no guesses.', '',
          '## Not research: decisions only a person can make', '',
          '- `data-sourcing/PENDING_DOMAIN_PROOFS.md`: secondary domains awaiting an ownership proof. Facts are already returned and accepted automatically once proven.',
          '- `data-sourcing/INGEST_REPORT.md` → Review queue: reviewer flags (Onfido manual sourcing; confirm the Gusto / Elastic Path / Gandi homepages) and records with no verifiable provider domain.']
    open(os.path.join(DS, 'REMAINING_DATA.md'), 'w').write('\n'.join(L) + '\n')
    print('\n'.join(L[:16]))


if __name__ == '__main__':
    main()
